### PR TITLE
Main homepage

### PR DESCRIPTION
**Pull request by Trictonicmp**
### In this pull request I:
* Added an index.html file
* Added a header to the index.html
* Added styles to the header

### CODE REVIEW

**Review by omar-muhamad — CHANGES_REQUESTED** [review]
# Changes Required ♻️
### Hi @Trictonicmp,

Great job so far, you are almost there.



## (Highlights) Good Points: :+1:
- You documented your work professionally. :heavy_check_mark:
- Github flow is used correctly. :heavy_check_mark:
- You added .html and .css files the right way. :heavy_check_mark:

## (Changes Required) Aspects to improve: ♻️

- [ ] Please set up [a linter for HTML and CSS](https://github.com/microverseinc/linters-config/tree/master/html-css) by adding `.github/workflows` directory and add `linters.yml` file inside this directory

image

- [ ] In the README file please remove `Install` and `Run Tests ` sections because you added the wrong info there and you will use them properly in the upcoming projects.

- [ ] In the README file Kindly remove unused sections like `Usage` and `Deployment` to make your readme file more professional.

- [ ] Kindly add` .gitignore` to your repo and make sure to add `test.md` file and `node_modules` directory inside `.gitignore` file like the project requirments.

image
image


## [Optional] suggestions:

- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by Trictonicmp** [comment]
> 

Hi, Thank you for your feedback, I'm working on it but github actions detect the folder "hint-report" and webhint shows errors from the files inside, do I have to .gitignore this folder?

**Comment by omar-muhamad** [comment]
Hi @Trictonicmp,
please remove webhint-report file from your repo and you can add it to .gitignore file.
To fix webhint errors open your terminal and run `npx hint .` and see what is casing the errors and fix it.

**Review by gemmen29 — APPROVED** [review]
Hi @Trictonicmp, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Optional suggestions

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
